### ISSUE TITLE
Removing Float calculations

### ISSUE THREAD

**Issue by kianenigma** [w3f/consensus#8]
If this algorithm is to be implemented on-chain, a little part of it having floating point arithmetic can cause a great deal of trouble; essentially forbidden.  Namely: 

```
                candidate.score=1/candidate.approvalstake
```

Is there a way (even sub-optimal) to circumvent this issue?

**Comment by burdges** [comment]
Oh?  Why?  An `f64`s should not produce undefined behavior, right?  

You can always clear denominators but doing so may make the code uglier unless you make a special type.

**Comment by kianenigma** [comment]
I should have emphasized on being **on-chain**; there f64 or generally float calculation is forbidden. Substrate currently has a fixed point utility trait/struct that can be used (`Perbill` etc.) Haven't gotten there yet but I think it will be ok even on-chain.

**Comment by burdges** [comment]
I see.  We should provide some interface that makes doing this correctly fairly painless, at least in Rust.  If there are any concerns then @drskalman and/or I can look into it.

**Comment by kianenigma** [comment]
Currently, this is implemented using a structure like this but with the accuracy of 10 to the power of 18
https://github.com/paritytech/substrate/blob/master/core/sr-primitives/src/lib.rs#L135
